// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9rl9bnvTAiwtwIlpdejGp2eIOSzYc1_o',
    appId: '1:1020007349278:web:c33bdd72cd2d6f77a1820f',
    messagingSenderId: '1020007349278',
    projectId: 'fir-course-cdd79',
    authDomain: 'fir-course-cdd79.firebaseapp.com',
    storageBucket: 'fir-course-cdd79.appspot.com',
    measurementId: 'G-47SNJ0294H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-jorno7gyUGk1FZUS3rJtsSLXoea038',
    appId: '1:1020007349278:android:57833fdbcde9ee15a1820f',
    messagingSenderId: '1020007349278',
    projectId: 'fir-course-cdd79',
    storageBucket: 'fir-course-cdd79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC48DoeU5MGgyzGGY2Bz5AHC8FH6yy2EWA',
    appId: '1:1020007349278:ios:fb530ae42697d237a1820f',
    messagingSenderId: '1020007349278',
    projectId: 'fir-course-cdd79',
    storageBucket: 'fir-course-cdd79.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC48DoeU5MGgyzGGY2Bz5AHC8FH6yy2EWA',
    appId: '1:1020007349278:ios:c74f4746aa623152a1820f',
    messagingSenderId: '1020007349278',
    projectId: 'fir-course-cdd79',
    storageBucket: 'fir-course-cdd79.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
